### ISSUE TITLE
ClickHouse parameterized view

### ISSUE THREAD

**Issue by flipchart** [TylerBrinks/SqlParser-cs#10]
I'd like to parse ClickHouse SQL which contains parameters for their [parameterized views](https://clickhouse.com/docs/en/sql-reference/statements/create/view#parameterized-view). The SQL looks like

`CREATE VIEW view AS SELECT * FROM TABLE WHERE Column1={column1:datatype1}`

Note the parameter is in the { } brackets. I get an exception. Is this easy to implement with a custom dialect, or would it need more significant changes to the parser?

**Comment by TylerBrinks** [comment]
It wouldn't be difficult, no.  However what I would suggest is posting it to the [https://github.com/sqlparser-rs/sqlparser-rs](SqlParser-rs) project because this is a clone of the Rust project and keeping in step with their codebase.  I don't mind deviations, and you could certainly extend the existing ClickHouse dialect, but that would turn out the best, most comprehensive solution.

**Comment by TylerBrinks** [comment]
Closing - this will track with the Rust project's implementation.

**Comment by flipchart** [comment]
FYI https://github.com/sqlparser-rs/sqlparser-rs/pull/1181
