### ISSUE TITLE
Support for passing in CultureInfo to parser

### ISSUE THREAD

**Issue by Ulimo** [TylerBrinks/SqlParser-cs#4]
Hi!
Great library, there seems to be an issue though when parsing numeric values.
In some languages comma "," is used as a delimeter, so '123.45' will not be parsed correctly into a double, instead it throws an exception.

If it would be possible to pass in CultureInfo one could pass in CultureInfo.InvariantCulture to be able to parse numeric values.
Another option would be to make the different parsing methods virtual to allow overriding certain methods.

**Comment by TylerBrinks** [comment]
I'm not sure culture information makes sense within the parser given CSS isn't a culture-specific language.  The goal of the library is to parse the raw CSS into an AST.  If you want to change number format, that would be best suited for code outside the library.   Otherwise you introduce transformations that don't exist in the CSS.  The parsed object model is one that, ideally, should be able to go from CSS text to memory and back again with very little lost in translation.  Granted, elements are normalized in some places.  However it wouldn't make sense to have a value such as `width: 33.5%` turn into `width: 33,5%`.  Doing so would render the CSS invalid.

**Comment by Ulimo** [comment]
Hi again!

This is about your sql parser and not the css parser :)
The problem is not that I want comma support, but rather dot delimeted fails when parsing.

say "field1 > 123.45" will throw an exception when parsing. So if '.' is the supported delimiter, then TryParse for double should then have CultureInfo.InvariantCulture

**Comment by TylerBrinks** [comment]
My apologies - too many parsers in my life. 

You have an interesting point. Let me see what I can come up with..

**Comment by TylerBrinks** [comment]
@Ulimo in your opinion does it make more sense to configure it globally or per parser instance?

**Comment by Ulimo** [comment]
Hi again!

Well per parser instance I guess is more generic and allows more use cases, but globally is easier to implement.
For my use case globally works fine, as you mentioned in the sql spec you should use '.' as a delimeter and not comma.

**Comment by TylerBrinks** [comment]
The latest version has been posted to nuget.org.  Numeric values with decimal precision are only parsed in one spot making it possible to add an invariant culture to that parsing routine.  The current package should parse your query regardless of culture.
