### ISSUE TITLE
Performance Issue with Heavy Use of MS SQL Built-in Functions in Queries

### ISSUE THREAD

**Issue by grcontin** [TylerBrinks/SqlParser-cs#48]
Hello again, sorry if I am causing any inconvenience, as this tool has made a huge difference in my project. After the release of version 0.6.0, the performance improvements have been significant. However, there is one case where this improvement did not occur, and I believe it is due to the high use of built-in functions in MS SQL within the query. Is there a way for me to configure the tool to possibly ignore the processing of these functions, or would I need to create an extension to handle this specific case? Below is the query for testing. Thank you very much for your support!!

```
WITH DateCalculations AS (
    SELECT 
        CAST(DATEADD(MONTH, -2, GETDATE()) AS DATE) AS TwoMonthsAgo,
        CAST(DATEADD(MONTH, -1, GETDATE()) AS DATE) AS LastMonth,
        FORMAT(GETDATE(), 'yyyy-MM-dd') AS CurrentDateFormatted,
        FORMAT(DATEADD(MONTH, -1, GETDATE()), 'yyyy-MM-dd') AS LastMonthFormatted,
        CAST(GETDATE() AS INT) AS CurrentDateInt,
        CONVERT(VARCHAR(7), GETDATE(), 120) AS CurrentYearMonth
),
ParticipantStats AS (
    SELECT 
        p.Id AS ParticipantId,
        p.Name AS ParticipantName,
        COUNT(pm.Id) AS TotalMonthlyBalances,
        SUM(pm.GrossQuotaQuantity) AS TotalGrossQuotaQuantity,
        MAX(pm.ReferenceYearMonth) AS LastBalanceMonth
    FROM Participants p
    LEFT JOIN ParticipantMonthlyBalances pm
        ON p.Id = pm.ParticipantId
    GROUP BY p.Id, p.Name
)
SELECT 
    ps.ParticipantId,
    ps.ParticipantName,
    ps.TotalMonthlyBalances,
    ps.TotalGrossQuotaQuantity,
    ps.LastBalanceMonth,
    dc.TwoMonthsAgo,
    dc.LastMonth,
    dc.CurrentDateFormatted,
    dc.LastMonthFormatted,
    dc.CurrentDateInt,
    dc.CurrentYearMonth,
    CASE 
        WHEN ps.TotalGrossQuotaQuantity > 100 THEN 'High'
        WHEN ps.TotalGrossQuotaQuantity BETWEEN 50 AND 100 THEN 'Medium'
        ELSE 'Low'
    END AS QuotaCategory,
    FORMAT(GETDATE(), 'yyyy-MM-dd') AS TodayFormatted,
    CONVERT(VARCHAR(20), GETDATE(), 120) AS CurrentDateISO
FROM ParticipantStats ps
CROSS JOIN DateCalculations dc
WHERE ps.LastBalanceMonth BETWEEN dc.LastMonthFormatted AND dc.CurrentDateFormatted
ORDER BY ps.ParticipantName;
```

**Comment by TylerBrinks** [comment]
Let me see if I can identify the source of the latency.  The engine allows external callers to supply a custom dialect where you can handle parsing however you prefer.  It wouldn't be a huge effort to create and use your own extended MsSql dialect.  Regardless, performance issues should be addressed.

You might be interested to pull down the source code and take a look at how queries are parsed.  I'm always happy to take PRs. 
 There's a comprehensive suite of unit tests making it difficult to break the parser.

**Comment by TylerBrinks** [comment]
@grcontin Can you add a little detail  on what you're seeing in terms if this query's performance?  With the change I published earlier, both queries (the one from the other issue) are parsing in under 25ms with my tests.

**Comment by grcontin** [comment]
The query is showing a variation between 800µs and 1ms for execution. The time ends up being relatively high due to the excessive use of built-in functions in MS SQL. When these functions are absent, the performance is significantly better, with some queries taking between 100 and 200µs. I conducted a benchmark and will share with you the exact setup I used for this query. I believe I might be doing something wrong, or perhaps the solution would be to write a custom dialect that specifically handles queries with a read-only characteristic.

![image](https://github.com/user-attachments/assets/120c5925-1b5b-44da-8f32-7a82b8b39c6c)

```
[Benchmark]
public void ParseGitIssueQuery()
{
    var parser = new Parser();
    var options = new ParserOptions
    {
        TrailingCommas = false,
        Unescape = false
    };

    Sequence<Statement> statements = parser.ParseSql(GitIssue, new MsSqlDialect(), options);
}
```

**Comment by TylerBrinks** [comment]
I'm still investigating the issue, but I don't have a concrete answer yet.  At first glance, it looks like the same `MaybeParseChecked` code is taking a reasonable percentage.  I haven't found any hotspots yet with the exception of the `ParseDataType` function.  It appears that call is taking the longest, and it's where I'm focusing my investigation.

Here's a quick dotTrace output from a unit test executing your query:

![image](https://github.com/user-attachments/assets/86faad35-b1bd-4943-bead-3fd7b9969f0d)

**Comment by TylerBrinks** [comment]
@grcontin I can say this much - the issue is related to the number of exceptions being thrown and caught within the parser.  In the case of this query, there are roughly 25 exceptions thrown (intentionally).  There are areas in the parser that raise exceptions when the expected token isn't encountered.  In the case of your query, it's within a switch statement looking for type modifiers.  Most of the engine's token checking exists within some variation of a switch block.  Exceptions are raised when those switch statements don't yield one of the valid tokens.  Typically that's desired, but not in this case where the exception represents control flow, not unrecoverable behavior.

With the issue we fixed the other day substituted an intentionally exception exception with an alternative output given how expensive the exception was.   As to why exceptions were used in the first place, the Rust project this codebase is based on uses Rust's union `Err` type.  These Rust `Err` flows are an example of where C# and Rust diverge.  Rust is returning a known union which is checked, but without the expense of throwing an error as in .NET.  The engine _should_ throw exceptions where the input is not valid.  However, the `MaybeParse` method really shouldn't depend on exceptions to reset the parser's index unless there is no other alternative.

I think in this case, tracking down the possible call stacks for the `ParseOptionalTypeModifiers` and `ParseIdentifierWithClause` and swapping the exceptions will fix the issue.

**Comment by grcontin** [comment]
Got it, now everything makes sense. If I’m not mistaken, the next version of .NET will also have discriminated unions, which would serve the same purpose as in RUST. While that feature is not available yet, I’ll think about how I can help diagnose the issue. I’ll run the project and analyze it as well to see if I can assist in any way

**Comment by TylerBrinks** [comment]
Here's a branch with an initial attempt that passes all unit tests, keeps exceptions intact when not using `MaybeParsed`, but suppresses throwing in that context.

https://github.com/TylerBrinks/SqlParser-cs/tree/exception-suppression

**Comment by TylerBrinks** [comment]
@grcontin Try the latest on NuGet.org, 0.6.1

**Comment by grcontin** [comment]
@TylerBrinks Now this is extremely fast, performing better than Microsoft's native parser. My sincere congratulations and thanks for all the support and hard work. The tool is simply amazing and very powerful, in addition to being incredibly simple to use. Once again, thank you very much, and Merry Christmas!

**Comment by TylerBrinks** [comment]
🎄
